### ISSUE TITLE
Feature: Support Frame1 controllers

### ISSUE THREAD

**Issue by OtaK** [OtaK/b0xx-viewer-rs#28]
## Waiting for spec / RE results

**Comment by IvantheTricourne** [comment]
I'm curious what kind of info you need to accomplish this. I recently got a frame1. Been an active user of your viewer with my B0XX. Happy to help.

**Comment by OtaK** [comment]
@IvantheTricourne Hi! That's a bit of an issue, as I completely retired from the melee community. I don't have access to a frame1 to reverse engineer the protocol, and I've not been on the best terms with its maker.

If someone would provide me the details of the serial protocol (byte -> input mapping, different states) that the frame1 runs over USB for input reporting, I'd be glad to do it, but otherwise, I won't ask Stephen nor buy a frame1 to do it, sorry :(

Also on other note, the frame1.gg website still has no documentation, no firmware updater, no viewer, nothing? Truth be told, Stephen (NB: aka Greg Turbo, founder of frame1) wanted to hire me to write his software, and I literally haven't heard from him in more than a year.

**Comment by OtaK** [comment]
As Frame1s are basically a scam with non-existent software and non-existent deliveries, not going to support that.

Will reopen one day if they move towards actually shipping stuff and delivering a feature-complete software. 

Note: There's still currently no way to display inputs on a 3rd party software without doing something crappy like [Windows Joystick API interpolation](https://github.com/coreyp7/Frame1-Input-Display). I have a draft of something like that but it's TERRIBLE and doesn't support other platforms than Windows.
